export const GET_CURRENT_POSITION_REQUEST = 'GET_CURRENT_POSITION_REQUEST';
export const GET_CURRENT_POSITION_SUCCESS = 'GET_CURRENT_POSITION_SUCCESS';
export const GET_CURRENT_POSITION_ERROR = 'GET_CURRENT_POSITION_ERROR';
